import * as THREE from 'three';
import { GLTFLoader, type GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { clone as skeletonClone } from 'three/examples/jsm/utils/SkeletonUtils.js';
import type { BodyBuild, CharacterBase, CharacterConfig } from '../types';
import { HAIR_COLORS } from '../data/catalog';
import { buildOutfitFit, type OutfitFit } from './outfitFit';
import { GARMENTS, buildGarment, fabricMaterial, joints, underwear } from './gymWear';

const BODY_URLS: Record<BodyBuild, Record<CharacterBase, string>> = {
  superhero: {
    male: '/models/characters/Superhero_Male_FullBody.gltf',
    female: '/models/characters/Superhero_Female_FullBody.gltf',
  },
  regular: {
    male: '/models/characters/Regular_Male_FullBody.gltf',
    female: '/models/characters/Regular_Female_FullBody.gltf',
  },
  teen: {
    male: '/models/characters/Teen_Male_FullBody.gltf',
    female: '/models/characters/Teen_Female_FullBody.gltf',
  },
};

// index -> complexion, in the same order as SKIN_TONES in data/catalog.ts
// (Light/Medium/Dark, then fantasy tones at high-level unlocks). Pre-
// composited by scripts/generate_complexion_textures.py (see
// public/models/characters/*_Complexion_*.png) from the pack's single
// base texture per build: a saturation-threshold mask separates real skin
// pixels (warm, saturated) from the baked-in default garment (near-
// neutral grey/black), then only the skin pixels get tinted toward the
// target tone via a color ratio - the garment stays fixed regardless of
// the chosen complexion, and this same mechanism works just as well for
// a fantasy target (blue, gold, ...) as a realistic one.
//
// TEXTURE_VERSION cache-busts these filenames: they're served with a 24h
// Cache-Control (see public/_headers) since they're not content-hashed
// like the JS bundle, so both the CDN edge and every visited browser can
// keep serving pre-fix bytes for up to a day after a real deploy unless
// the URL itself changes. Bump this whenever generate_complexion_textures
// output changes.
const TEXTURE_VERSION = 3;
const COMPLEXION_TONES = ['Light', 'Medium', 'Dark', 'Blue', 'Gold', 'Emerald', 'Crimson'];

function skinTextureName(build: BodyBuild, base: CharacterBase, skin: number): string {
  const buildName = build[0].toUpperCase() + build.slice(1);
  const baseName = base[0].toUpperCase() + base.slice(1);
  const tone = COMPLEXION_TONES[Math.max(0, Math.min(COMPLEXION_TONES.length - 1, skin))];
  return `/models/characters/T_${buildName}_${baseName}_Complexion_${tone}.png?v=${TEXTURE_VERSION}`;
}

// Recolored variants generated by scripts/generate_outfit_textures.py -
// index 0 ('default') is the pack's own unmodified texture, no file to
// swap in for it (see OUTFIT_COLOR_FILES below).
const OUTFIT_TEXTURE_VERSION = 3;
const OUTFIT_COLOR_FILES = ['default', 'Charcoal', 'Crimson', 'Forest', 'Slate', 'Gold'];
const OUTFIT_FILE_PREFIX: Record<string, string> = {
  trainer: 'Peasant',
  ranger: 'Ranger',
  noble: 'Noble',
  wizard: 'Wizard',
  knight: 'Knight',
};

function outfitColorTextureName(outfit: string, colorIdx: number): string | null {
  const name = OUTFIT_COLOR_FILES[Math.max(0, Math.min(OUTFIT_COLOR_FILES.length - 1, colorIdx))];
  if (name === 'default') return null;
  const prefix = OUTFIT_FILE_PREFIX[outfit];
  const folder = outfit === 'trainer' ? 'peasant' : outfit;
  if (!prefix) return null;
  return `/models/outfits/${folder}/T_${prefix}_${name}_BaseColor.png?v=${OUTFIT_TEXTURE_VERSION}`;
}

const ANIMATIONS_URL = '/models/animations/UAL1_Standard.glb';

// Clip names from Quaternius's Universal Animation Library - shares the base
// characters' skeleton (verified matching joint names), so clips apply with
// no retargeting.
export const CLIPS = {
  idle: 'Idle_Loop',
  run: 'Jog_Fwd_Loop',
  flex: 'Dance_Loop',
} as const;

const HAIR_URLS: Record<string, string> = {
  buzzed: '/models/hair/Hair_Buzzed.gltf',
  dreads: '/models/hair/Hair_Dreads.gltf',
  mohawk: '/models/hair/Hair_Mohawk.gltf',
  ponytail: '/models/hair/Hair_Ponytail.gltf',
  simpleParted: '/models/hair/Hair_SimpleParted.gltf',
  slickBack: '/models/hair/Hair_SlickBack.gltf',
  bob: '/models/hair/Hair_Bob.gltf',
  buns: '/models/hair/Hair_Buns.gltf',
  buzzedFemale: '/models/hair/Hair_BuzzedFemale.gltf',
  long: '/models/hair/Hair_Long.gltf',
  longDreads: '/models/hair/Hair_LongDreads.gltf',
  ponytail2: '/models/hair/Hair_Ponytail_2.gltf',
};

// Each outfit is the pack's own assembled outfit file - every piece the pack's
// author put in that outfit (boots, pauldrons, gorget, scarf, ...), exactly as
// shipped in Outfits/{Gender}_{Name}.gltf of the Modular Character Outfits pack.
// They are all bound to the Regular skeleton; see outfitFit.ts for how they're
// fitted to the other builds.
const OUTFIT_URLS: Record<string, Record<CharacterBase, string>> = {
  trainer: {
    male: '/models/outfits/peasant/Male_Peasant_Outfit.gltf',
    female: '/models/outfits/peasant/Female_Peasant_Outfit.gltf',
  },
  ranger: {
    male: '/models/outfits/ranger/Male_Ranger_Outfit.gltf',
    female: '/models/outfits/ranger/Female_Ranger_Outfit.gltf',
  },
  noble: {
    male: '/models/outfits/noble/Male_Noble_Outfit.gltf',
    female: '/models/outfits/noble/Female_Noble_Outfit.gltf',
  },
  wizard: {
    male: '/models/outfits/wizard/Male_Wizard_Outfit.gltf',
    female: '/models/outfits/wizard/Female_Wizard_Outfit.gltf',
  },
  knight: {
    male: '/models/outfits/knight/Male_Knight_Outfit.gltf',
    female: '/models/outfits/knight/Female_Knight_Outfit.gltf',
  },
};

// The pack's readme: "When using the clothing, only the head of the model is
// required. Using the full body will result in clipping." So a clothed character
// is drawn as head-only plus the outfit. Teen and Regular ship their own
// head-only meshes. Superhero doesn't, so it borrows Regular's - the two heads
// match to within 4mm - and that borrowed neck is fitted to Superhero's
// shoulders along with the outfit.
const HEAD_URLS: Record<BodyBuild, Record<CharacterBase, string>> = {
  superhero: {
    male: '/models/characters/Regular_Male_OnlyHead.gltf',
    female: '/models/characters/Regular_Female_OnlyHead.gltf',
  },
  regular: {
    male: '/models/characters/Regular_Male_OnlyHead.gltf',
    female: '/models/characters/Regular_Female_OnlyHead.gltf',
  },
  teen: {
    male: '/models/characters/Teen_Male_OnlyHead.gltf',
    female: '/models/characters/Teen_Female_OnlyHead.gltf',
  },
};

const loader = new GLTFLoader();
const gltfCache = new Map<string, Promise<GLTF>>();
function loadGLTF(url: string): Promise<GLTF> {
  let p = gltfCache.get(url);
  if (!p) {
    p = new Promise((resolve, reject) => loader.load(url, resolve, undefined, reject));
    gltfCache.set(url, p);
  }
  return p;
}

const textureLoader = new THREE.TextureLoader();
const textureCache = new Map<string, Promise<THREE.Texture>>();
// Returns a Promise, not a bare Texture: TextureLoader.load() returns
// immediately with the image still loading in the background, which is
// fine for the live animated view (a later frame just picks up the
// loaded texture) but broke the one-shot thumbnail snapshot render -
// it rendered (and permanently cached) a frame captured before the
// texture arrived, showing a flat black silhouette forever.
function loadSkinTexture(url: string): Promise<THREE.Texture> {
  let p = textureCache.get(url);
  if (!p) {
    p = new Promise((resolve, reject) => {
      textureLoader.load(
        url,
        (tex) => {
          tex.colorSpace = THREE.SRGBColorSpace;
          tex.flipY = false;
          resolve(tex);
        },
        undefined,
        reject,
      );
    });
    textureCache.set(url, p);
  }
  return p;
}

const SKIN_MATERIAL_RE = /^MI_(Superhero|Regular|Teen)_(Male|Female)$/;

// Rest-pose pelvis position in the animation library's own rig, read from its file.
let animPelvisRest: THREE.Vector3 | null = null;

export function loadAnimationClips(): Promise<THREE.AnimationClip[]> {
  return loadGLTF(ANIMATIONS_URL).then((g) => {
    if (!animPelvisRest) {
      const node = (g.parser.json.nodes as { name?: string; translation?: number[] }[]).find((n) => n.name === 'pelvis');
      animPelvisRest = new THREE.Vector3().fromArray(node?.translation ?? [0, 0, 1]);
    }
    return g.animations;
  });
}

// The library's clips key translation (and scale) on all 65 bones, recorded on
// one fixed rig. Played raw, they overwrite each build's own bone lengths, so
// Teen got stretched to adult size and every build got that rig's proportions.
// Returns clips that keep rotations only, plus the pelvis motion rescaled to this
// character's own hip height. Call with the group composeCharacter returned.
const fittedClipCache = new WeakMap<THREE.AnimationClip, Map<string, THREE.AnimationClip>>();
export function fitClipsToCharacter(clips: THREE.AnimationClip[], group: THREE.Object3D): THREE.AnimationClip[] {
  const pelvisRest = group.userData.pelvisRest as THREE.Vector3 | undefined;
  if (!pelvisRest || !animPelvisRest) return clips;
  const anim = animPelvisRest;
  const k = pelvisRest.length() / anim.length();
  const cacheKey = pelvisRest.toArray().map((v) => v.toFixed(5)).join(',');
  return clips.map((clip) => {
    let perClip = fittedClipCache.get(clip);
    if (!perClip) fittedClipCache.set(clip, (perClip = new Map()));
    const hit = perClip.get(cacheKey);
    if (hit) return hit;
    const tracks: THREE.KeyframeTrack[] = [];
    for (const t of clip.tracks) {
      const [bone, prop] = t.name.split('.');
      if (prop === 'quaternion') tracks.push(t);
      else if (prop === 'position' && bone === 'pelvis') {
        const v = t.values.slice();
        for (let i = 0; i < v.length; i += 3) {
          v[i] = pelvisRest.x + (v[i] - anim.x) * k;
          v[i + 1] = pelvisRest.y + (v[i + 1] - anim.y) * k;
          v[i + 2] = pelvisRest.z + (v[i + 2] - anim.z) * k;
        }
        tracks.push(new THREE.VectorKeyframeTrack(t.name, t.times as unknown as number[], v as unknown as number[]));
      }
    }
    const fitted = new THREE.AnimationClip(clip.name, clip.duration, tracks);
    perClip.set(cacheKey, fitted);
    return fitted;
  });
}

function findSkinnedMeshes(root: THREE.Object3D): THREE.SkinnedMesh[] {
  const out: THREE.SkinnedMesh[] = [];
  root.traverse((o) => {
    if ((o as THREE.SkinnedMesh).isSkinnedMesh) out.push(o as THREE.SkinnedMesh);
  });
  return out;
}

// Rebuilds `mesh` (optionally with a replacement geometry) bound to the master
// skeleton's bones, matched by name, so it deforms in lockstep with the body.
// Outfits, heads and hair share the base bodies' rig family (identical joint
// names), and keep their own inverse bind matrices.
function attachToSkeleton(
  mesh: THREE.SkinnedMesh,
  boneByName: Map<string, THREE.Bone>,
  geometry: THREE.BufferGeometry = mesh.geometry,
): THREE.SkinnedMesh | null {
  const srcSkeleton = mesh.skeleton;
  const bones = srcSkeleton.bones.map((b) => boneByName.get(b.name));
  if (bones.some((b) => !b)) return null;
  const attached = new THREE.SkinnedMesh(geometry, mesh.material);
  attached.castShadow = false;
  attached.receiveShadow = false;
  const skeleton = new THREE.Skeleton(bones as THREE.Bone[], srcSkeleton.boneInverses);
  attached.bind(skeleton, mesh.bindMatrix);
  return attached;
}

// Fitting is pure geometry work, so it's done once per build and cached: one fit
// per gender+build, and one fitted geometry per source mesh per build.
const fitCache = new Map<string, Promise<OutfitFit>>();
const fittedGeometryCache = new Map<string, THREE.BufferGeometry>();
function getOutfitFit(build: BodyBuild, base: CharacterBase): Promise<OutfitFit> {
  const key = `${build}|${base}`;
  let p = fitCache.get(key);
  if (!p) {
    p = Promise.all([loadGLTF(BODY_URLS.regular[base]), loadGLTF(BODY_URLS[build][base])]).then(([r, t]) =>
      buildOutfitFit(r.scene, t.scene),
    );
    fitCache.set(key, p);
  }
  return p;
}
function fittedGeometry(fit: OutfitFit, mesh: THREE.SkinnedMesh, key: string): THREE.BufferGeometry {
  let g = fittedGeometryCache.get(key);
  if (!g) fittedGeometryCache.set(key, (g = fit.fitGeometry(mesh)));
  return g;
}

// Gym wear: garments are generated from the build's own body (see gymWear.ts), once per
// base+build+garment, and cached. With shoes on, the feet inside them aren't drawn.
const gymGeoCache = new Map<string, THREE.BufferGeometry | null>();
const footlessCache = new Map<string, THREE.BufferGeometry>();
function gymGarment(srcSkin: THREE.SkinnedMesh, key: string, base: CharacterBase, build: BodyBuild): THREE.BufferGeometry | null {
  const ck = `${base}|${build}|${key}`;
  if (!gymGeoCache.has(ck)) {
    const spec = GARMENTS[key];
    // per-build tweaks (e.g. Athletic only), exactly as approved in the Gym Wardrobe artifact
    const bspec = spec?.perBuild?.[build] ? { ...spec, ...spec.perBuild[build] } : spec;
    gymGeoCache.set(ck, bspec ? buildGarment(bspec, srcSkin, joints(srcSkin)) : null);
  }
  return gymGeoCache.get(ck)!;
}
function footless(srcSkin: THREE.SkinnedMesh, base: CharacterBase, build: BodyBuild): THREE.BufferGeometry {
  const ck = `${base}|${build}`;
  let g = footlessCache.get(ck);
  if (!g) {
    const J = joints(srcSkin), full = srcSkin.geometry, pos = full.attributes.position, idx = full.index!.array;
    const cut = J.foot.y + GARMENTS.trainers.collar - 0.012, keep: number[] = [];
    for (let t = 0; t < idx.length; t += 3) {
      if (!(pos.getY(idx[t]) < cut && pos.getY(idx[t + 1]) < cut && pos.getY(idx[t + 2]) < cut)) keep.push(idx[t], idx[t + 1], idx[t + 2]);
    }
    g = full.clone();
    g.setIndex(keep);
    footlessCache.set(ck, g);
  }
  return g;
}

export interface ComposedCharacter {
  group: THREE.Group;
}

export async function composeCharacter(cfg: CharacterConfig): Promise<ComposedCharacter> {
  const bodyGltf = await loadGLTF(BODY_URLS[cfg.build][cfg.base]);
  const bodyScene = skeletonClone(bodyGltf.scene) as THREE.Group;

  const bodySkinned = findSkinnedMeshes(bodyScene);
  bodySkinned.forEach((m) => {
    m.castShadow = true;
    m.receiveShadow = true;
  });

  const boneByName = new Map<string, THREE.Bone>();
  bodySkinned[0]?.skeleton.bones.forEach((b) => boneByName.set(b.name, b));

  const group = new THREE.Group();
  group.add(bodyScene);
  // Bind-pose pelvis, captured before any animation touches it - used by
  // fitClipsToCharacter to keep this build's own proportions.
  const pelvis = boneByName.get('pelvis');
  if (pelvis) group.userData.pelvisRest = pelvis.position.clone();

  // Skin tone: retarget skin materials (named MI_{Build}_{Base}) onto the
  // complexion texture. Skips MI_Eyes/MI_Hair_* (eyebrows, eyes). The texture
  // must match the UV layout of the mesh it goes on - which is the build the
  // mesh came from, not necessarily cfg.build: a borrowed Regular head, and
  // the hand/forearm patches baked into outfit pieces, are Regular meshes.
  const skinTexFor = (build: BodyBuild) => loadSkinTexture(skinTextureName(build, cfg.base, cfg.skin));
  const applySkin = async (meshes: THREE.SkinnedMesh[], build: BodyBuild) => {
    const tex = await skinTexFor(build);
    meshes.forEach((m) => {
      const mat = m.material as THREE.MeshStandardMaterial;
      if (!mat?.map || !SKIN_MATERIAL_RE.test(mat.name || '')) return;
      const cloned = mat.clone();
      cloned.map = tex;
      m.material = cloned;
    });
  };

  const outfitUrl = cfg.outfit !== 'none' ? OUTFIT_URLS[cfg.outfit]?.[cfg.base] : undefined;

  if (!outfitUrl) {
    await applySkin(bodySkinned, cfg.build);
    // Gym wear goes over the Default outfit only.
    const srcSkin = findSkinnedMeshes(bodyGltf.scene).find((m) => SKIN_MATERIAL_RE.test((m.material as THREE.Material).name));
    const skin = bodySkinned.find((m) => SKIN_MATERIAL_RE.test((m.material as THREE.Material).name));
    if (srcSkin && skin) {
      const J = joints(srcSkin), U = underwear(srcSkin, J);
      for (const key of [cfg.bottom, cfg.top, cfg.shoes]) {
        if (!key || key === 'none' || !GARMENTS[key]) continue;
        const geo = gymGarment(srcSkin, key, cfg.base, cfg.build);
        if (!geo) continue;
        const mesh = new THREE.SkinnedMesh(geo, fabricMaterial(GARMENTS[key], GARMENTS[key].color, J, U));
        mesh.bind(skin.skeleton, skin.bindMatrix);
        mesh.castShadow = true;
        mesh.receiveShadow = true;
        mesh.frustumCulled = false;
        group.add(mesh);
      }
      if (cfg.shoes && cfg.shoes !== 'none') skin.geometry = footless(srcSkin, cfg.base, cfg.build);
    }
  } else {
    // Clothed: the full body only provides the skeleton; head-only mesh + outfit
    // are drawn (see HEAD_URLS). Regular wears the pack's files unmodified.
    bodySkinned.forEach((m) => (m.visible = false));
    const [headGltf, outfitGltf, fit] = await Promise.all([
      loadGLTF(HEAD_URLS[cfg.build][cfg.base]),
      loadGLTF(outfitUrl),
      cfg.build === 'regular' ? Promise.resolve(null) : getOutfitFit(cfg.build, cfg.base),
    ]);

    const headBuild: BodyBuild = cfg.build === 'teen' ? 'teen' : 'regular';
    const headMeshes = findSkinnedMeshes(headGltf.scene)
      .map((m, i) => {
        // Only a borrowed head (Superhero) needs fitting; Teen's is its own.
        const geo = fit && cfg.build === 'superhero' ? fittedGeometry(fit, m, `head|${cfg.build}|${cfg.base}|${i}`) : m.geometry;
        return attachToSkeleton(m, boneByName, geo);
      })
      .filter((m): m is THREE.SkinnedMesh => !!m);
    headMeshes.forEach((m) => {
      m.castShadow = true;
      m.receiveShadow = true;
      group.add(m);
    });
    await applySkin(headMeshes, headBuild);

    const outfitColorUrl = outfitColorTextureName(cfg.outfit, cfg.outfitColor ?? 0);
    const outfitColorTex = outfitColorUrl ? await loadSkinTexture(outfitColorUrl) : undefined;
    const outfitMeshes: THREE.SkinnedMesh[] = [];
    const accessories = new Set<THREE.SkinnedMesh>();
    findSkinnedMeshes(outfitGltf.scene).forEach((m, i) => {
      const geo = fit ? fittedGeometry(fit, m, `${outfitUrl}|${cfg.build}|${i}`) : m.geometry;
      const attached = attachToSkeleton(m, boneByName, geo);
      if (!attached) return;
      outfitMeshes.push(attached);
      // Pack accessories (pauldrons, gorget, scarf) are metal/leather the outfit
      // recolour textures were never made for - recolouring tints the metal.
      if (/_Acc_/.test(m.name) || /_Acc_/.test(m.parent?.name ?? '')) accessories.add(attached);
    });
    outfitMeshes.forEach((m) => {
      // The body underneath is hidden, so the outfit has to cast the shadow.
      m.castShadow = true;
      m.receiveShadow = true;
      const mat = m.material as THREE.MeshStandardMaterial;
      if (outfitColorTex && mat?.map && !SKIN_MATERIAL_RE.test(mat.name || '') && !accessories.has(m)) {
        // Outfit color: the garment's BaseColor texture has real baked-in fabric
        // color (not a neutral tint base), so swap in a whole recolored texture
        // (see generate_outfit_textures.py) rather than multiplying a color.
        const cloned = mat.clone();
        cloned.map = outfitColorTex;
        m.material = cloned;
      }
      group.add(m);
    });
    // Hand/forearm skin baked into some outfit pieces is modeled on Regular.
    await applySkin(outfitMeshes, 'regular');
  }

  // The Knight's armet is a closed helmet; any hair would spike through it.
  const hairHidden = !!outfitUrl && cfg.outfit === 'knight';
  if (cfg.hair !== 'none' && HAIR_URLS[cfg.hair] && !hairHidden) {
    const idx = Math.max(0, Math.min(HAIR_COLORS.length - 1, cfg.hairColor ?? 0));
    const tint = HAIR_COLORS[idx].hex;
    const hairGltf = await loadGLTF(HAIR_URLS[cfg.hair]);
    findSkinnedMeshes(hairGltf.scene).forEach((m) => {
      const attached = attachToSkeleton(m, boneByName);
      if (!attached) return;
      // The hair texture is a near-neutral grey made for tinting, so a material
      // color multiply is enough - no separate texture per color needed.
      const cloned = (attached.material as THREE.MeshStandardMaterial).clone();
      cloned.color.set(tint);
      attached.material = cloned;
      group.add(attached);
    });
  }

  return { group };
}
