import type { CatalogKey, CharTier, HairItem, CatalogItem, OutfitItem, BodyBuild } from '../types';

export const CHAR_TIERS: CharTier[] = [
  { min: 1, name: 'Novice', c1: '#4f7fd4', c2: '#1c3d86' },
  { min: 6, name: 'Ascending', c1: '#2f7ff0', c2: '#0b2f8e' },
  { min: 12, name: 'Forged', c1: '#23b6c8', c2: '#124a96' },
  { min: 20, name: 'Vanguard', c1: '#e0a33c', c2: '#8a4a12' },
  { min: 28, name: 'Champion', c1: '#e0533c', c2: '#7a1d12' },
  { min: 36, name: 'Elite', c1: '#9b59e0', c2: '#3b1373' },
  { min: 45, name: 'Legend', c1: '#2fd0a0', c2: '#0c5a45' },
  { min: 55, name: 'Mythic', c1: '#f0d060', c2: '#6b5410' },
];

// index maps 1:1 to the baked Complexion textures generated by
// scripts/generate_complexion_textures.py (Light/Medium/Dark plus fantasy
// tones at high-level unlocks) - `id` unused for selection, same reason
// as HAIR_COLORS/OUTFIT_COLORS below. Free tones stay first so onboarding
// (which only ever shows the unconditionally-available ones) can just
// filter out anything with an `unlock`.
export const SKIN_TONES: (CatalogItem & { hex: string })[] = [
  { id: 'light', name: 'Light', hex: '#e8bd98' },
  { id: 'medium', name: 'Medium', hex: '#b57c50' },
  { id: 'dark', name: 'Dark', hex: '#6b4429' },
  { id: 'blue', name: 'Blue', hex: '#466ed8', unlock: { prestige: 1 } },
  { id: 'gold', name: 'Gold', hex: '#d4af57', unlock: { prestige: 1 } },
  { id: 'emerald', name: 'Emerald', hex: '#2e9e6e', unlock: { prestige: 2 } },
  { id: 'crimson', name: 'Crimson', hex: '#b2303e', unlock: { prestige: 2 } },
];

// Hair meshes ship with a near-neutral grey base texture (mean ~ (143,144,141),
// no baked-in color) made for tinting - applied as a material color multiply,
// not a separate texture per color like Complexion needed. `id` is unused for
// selection (character.hairColor stores an array index, not a string id -
// unlike every other wardrobe field), it's only here so these entries satisfy
// CatalogItem and can share isUnlocked/unlockLabel/countUnlocked with the
// rest of the wardrobe.
export const HAIR_COLORS: (CatalogItem & { hex: string })[] = [
  { id: 'black', name: 'Black', hex: '#1b1712' },
  { id: 'darkBrown', name: 'Dark Brown', hex: '#3d2a1c' },
  { id: 'brown', name: 'Brown', hex: '#6f4a2f' },
  { id: 'auburn', name: 'Auburn', hex: '#8a3f28' },
  { id: 'blonde', name: 'Blonde', hex: '#cfa15e' },
  { id: 'grey', name: 'Grey', hex: '#9b978f' },
  { id: 'green', name: 'Green', hex: '#2fae54', unlock: { level: 7 } },
  { id: 'blue', name: 'Blue', hex: '#2f83d8', unlock: { level: 13 } },
  { id: 'purple', name: 'Purple', hex: '#8a44d8', unlock: { level: 18 } },
  { id: 'pink', name: 'Pink', hex: '#e0559c', unlock: { level: 22 } },
];

export const BODY_BUILDS: (CatalogItem & { id: BodyBuild })[] = [
  { id: 'regular', name: 'Regular' },
  { id: 'teen', name: 'Teen' },
  { id: 'superhero', name: 'Athletic', unlock: { level: 8 } },
];

export const HAIR_STYLES: HairItem[] = [
  { id: 'none', name: 'None' },
  { id: 'buzzed', name: 'Buzzed', base: 'male' },
  { id: 'dreads', name: 'Dreads', base: 'male' },
  { id: 'mohawk', name: 'Mohawk', base: 'male', unlock: { level: 10 } },
  { id: 'ponytail', name: 'Ponytail', base: 'male' },
  { id: 'simpleParted', name: 'Parted', base: 'male' },
  { id: 'slickBack', name: 'Slick back', base: 'male', unlock: { level: 5 } },
  { id: 'bob', name: 'Bob', base: 'female' },
  { id: 'buns', name: 'Buns', base: 'female' },
  { id: 'buzzedFemale', name: 'Buzzed', base: 'female' },
  { id: 'long', name: 'Long', base: 'female' },
  { id: 'longDreads', name: 'Long dreads', base: 'female' },
  { id: 'ponytail2', name: 'Ponytail', base: 'female', unlock: { level: 5 } },
];

export const OUTFITS: OutfitItem[] = [
  { id: 'none', name: 'Default' },
  { id: 'trainer', name: 'Trainer kit' },
  { id: 'ranger', name: 'Ranger', unlock: { level: 15 } },
  { id: 'noble', name: 'Noble', unlock: { level: 17 } },
  { id: 'knight', name: 'Knight', unlock: { prestige: 1 } },
  { id: 'wizard', name: 'Wizard', unlock: { prestige: 2 } },
];

// Recolored BaseColor variants generated by scripts/generate_outfit_textures.py
// (each outfit's whole texture is fabric, unlike the body's - no skin mask
// needed, see the script's own docstring). 'default' means "use the pack's
// own unmodified texture", no file to load, so it has no matching PNG.
export const OUTFIT_COLORS: (CatalogItem & { hex: string })[] = [
  { id: 'default', name: 'Original', hex: '#6b5a4a' },
  { id: 'charcoal', name: 'Charcoal', hex: '#3a3a3f' },
  { id: 'crimson', name: 'Crimson', hex: '#a5293a', unlock: { level: 9 } },
  { id: 'forest', name: 'Forest', hex: '#2f6b3f', unlock: { level: 14 } },
  { id: 'slate', name: 'Slate', hex: '#3d5a73', unlock: { prestige: 1 } },
  { id: 'gold', name: 'Gold', hex: '#c9962f', unlock: { prestige: 1 } },
];

// Gym wear (see lib/gymWear.ts). Ids match its GARMENTS keys; men's and women's versions of a
// piece are separate garments, so each item is tied to one base, like hair styles.
export const GYM_TOPS: HairItem[] = [
  { id: 'none', name: 'None' },
  { id: 'cropTight', name: 'Crop (tight)', base: 'female' },
  { id: 'cropLoose', name: 'Crop (loose)', base: 'female' },
  { id: 'singletTight', name: 'Singlet', base: 'female' },
  { id: 'teeLoose', name: 'Tee', base: 'female' },
  { id: 'singletTightM', name: 'Singlet (tight)', base: 'male' },
  { id: 'singletLoose', name: 'Singlet (loose)', base: 'male' },
  { id: 'teeTight', name: 'Tee (tight)', base: 'male' },
  { id: 'teeLooseM', name: 'Tee (loose)', base: 'male' },
];
export const GYM_BOTTOMS: HairItem[] = [
  { id: 'none', name: 'None' },
  { id: 'leggingsLong', name: 'Leggings', base: 'female' },
  { id: 'leggingsShort', name: 'Bike shorts', base: 'female' },
  { id: 'shorts', name: 'Shorts', base: 'female' },
  { id: 'bikeShortsMale', name: 'Bike shorts', base: 'male' },
  { id: 'shortsMale', name: 'Shorts', base: 'male' },
  { id: 'trackpants', name: 'Track pants' },
];
export const GYM_SHOES: CatalogItem[] = [
  { id: 'none', name: 'Barefoot' },
  { id: 'trainers', name: 'Trainers' },
];

export const CATALOG: Record<CatalogKey, CatalogItem[]> = {
  top: GYM_TOPS,
  bottom: GYM_BOTTOMS,
  shoes: GYM_SHOES,
  hair: HAIR_STYLES,
  outfit: OUTFITS,
  build: BODY_BUILDS,
  hairColor: HAIR_COLORS,
  outfitColor: OUTFIT_COLORS,
  skin: SKIN_TONES,
};
